// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBRXB1u4QyVV8QAlGD4A_kEukPoaPdVYgc',
    appId: '1:796957490545:web:4a38392915644bd9448ad0',
    messagingSenderId: '796957490545',
    projectId: 'computeronlinestore-ppbfinal',
    authDomain: 'computeronlinestore-ppbfinal.firebaseapp.com',
    storageBucket: 'computeronlinestore-ppbfinal.appspot.com',
    measurementId: 'G-KSWXWQXMSS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCaWYx7R5C8J9RODH-YAcFWrQ8O3WbNef4',
    appId: '1:796957490545:android:0c2dac5cba676786448ad0',
    messagingSenderId: '796957490545',
    projectId: 'computeronlinestore-ppbfinal',
    storageBucket: 'computeronlinestore-ppbfinal.appspot.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBRXB1u4QyVV8QAlGD4A_kEukPoaPdVYgc',
    appId: '1:796957490545:web:0e207eb7e78a2158448ad0',
    messagingSenderId: '796957490545',
    projectId: 'computeronlinestore-ppbfinal',
    authDomain: 'computeronlinestore-ppbfinal.firebaseapp.com',
    storageBucket: 'computeronlinestore-ppbfinal.appspot.com',
    measurementId: 'G-FDH11G2PL8',
  );
}
